#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.



server:
  port: 8080

spring:
  application:
    name: bankcards
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
    info:
      title: Bank Cards API
      description: API for managing bank cards and users
      version: 1.0.0
      contact:
        name: Bank Cards Team
        email: support@bankcards.com
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter:
  show-actuator: true